name: 'social_media_reporting'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
#   twitter_posts_report: "{{ ref('twitter_organic__tweets') }}"
  facebook_posts_report: "{{ ref('facebook_pages__posts_report') }}"
  linkedin_posts_report: "{{ ref('linkedin_pages__posts') }}"
  instagram_posts_report: "{{ ref('instagram_business__posts') }}"
  
  social_media_rollup__twitter_enabled: False
  social_media_rollup__facebook_enabled: True
  social_media_rollup__linkedin_enabled: True
  social_media_rollup__instagram_enabled: True
  
  facebook_pages_schema: facebook_pages
    

  ##LinkedIn Pages schema and database variables
  linkedin_pages_schema: linkedin_company_pages
    

  ##Instagram Business schema and database variables
  instagram_business_schema: instagram
  
models:
  social_media_reporting:
    +schema: social_media_reporting
    +materialized: table 
    twitter_organic:
        enabled: false
    twitter_organic_source:
        enabled: false
    
    
    
